### PR TITLE
Patch 5

### PR DESCRIPTION
**Pull request by joel16**
I've cleaned up some bits and fixed some issues with the font blurring out. Once you have merged this into your repository, send me a pull request to my master branch and I'll merge it all :)

### CODE REVIEW

**Comment by Wolfvak** [comment]
I'll just fix a tiny mistake in the Makefile, and I've been thinking of removing the "place" var found here https://github.com/Wolfvak/Cyanogen3DS/blob/master/source/main.h#L6 and just default to SF2D_PLACE_RAM, since if you use VRAM there's a lot more steps involved (copying from VRAM to RAM and vice-versa, etc.). Should make it just a bit easier to add PNGs, or rather make it look easier.
Unfortunately I don't have a devkitPro setup right now so I can't test my modification, but I'll leave it up to you if you decide it to keep it that way :).

Merged.

**Comment by joel16** [comment]
Hmm, I'd like to have a look at your modification. I thought we have always been using RAM instead of VRAM though haha.

**Comment by Wolfvak** [comment]
Exactly, I still can't remember what I was thinking when I got the place var in there. Maybe I thought it'd be too slow to handle solely in RAM?

Regardless, the modificatio is easy, just replace
`#define load_PNG(texture, fname, mode) {texture = sfil_load_PNG_file(fname, mode); sf2d_texture_tile32(texture);}`
with
`#define load_PNG(texture, fname) {texture = sfil_load_PNG_file(fname, SF2D_PLACE_RAM); sf2d_texture_tile32(texture);}`
as well as replace all instances of load_PNG to remove the third argument (which is always SF2D_PLACE_RAM due to poor planning from my part)

I've also been thinking of making it a fully-blown function, in order to have return codes and to be able to check whether graphics exist . I'm actually not sure what would happen if a file is missing from romfs, and this would help a lot, so in case a texture file can't be found just create that sf2d_texture as a 64x64 (completely arbitrary, I'm just giving an example here) which is filled with gray or something, just to indicate that the texture file could not be loaded. You could also make it so that if the texture is too big, return another error code and make the texture a 64x64 but filled with another color, in order to give the user a clue as to what's wrong.

One of my ideas with moving everything to romfs was to make it more customizable, maybe even add themes or something like that.

**Comment by Wolfvak** [comment]
Some work has begun based in my little suggestions, all of the code was tested on an o3DS with HBL cia as *hax 2.6 entrypoint.
I still can't figure out how to detect the ninjhax version, but if CIA builds become a thing I doubt it'll be important.

https://github.com/Wolfvak/Cyanogen3DS/commit/f6aa4fcc16996cf7e72ec757ea9b8107db1fb498

**Comment by joel16** [comment]
Hm, looks fine to me. However I inserted those 'redeclarations' of fonts for a reason. I don't know if you noticed but the fonts tend to look blurry when they're using in different sizes. This is a problem with sftd lib, and a simple work around would be to re declare new fonts, using the same font and size. That's why I had it like that. I haven't figured out how to detect ninjahax version either, but isn't there a way to detect sys version? I was reading up a bit on ctrulib's documentation and I'm sure I saw it somewhere, but what I used didn't work haha.
Also do you know how to exit to hb launcher by any chance?

**Comment by Wolfvak** [comment]
Yeah, I didn't notice the blurry fonts (sucky vision) but I did check out sftdlib's source as well as it's issues; it's right here https://github.com/xerpi/sftdlib/issues/8. If that gets fixed then Cyanogen3DS' source gets quite simpler (given that the same font was read about 3-4 times other than the main one)

As with ninjhax, there's no way to actually detect it, which makes sense given that ctrulib isn't *hax dependant but rather a generic homebrew app for the 3DS. I've already asked about this and got no response.

The system firmware one is quite easy, this include should provide all needed info https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds/os.h#L8

And the exit to hb launcher is done by returning from main(), that's the only way I know (except the magical key combo, L+R+Down+B, but that's not particularly user-friendly right :P)
hbExit() only closes the hb service handle, which is not really useful to us. You'd need to break; your way out back to main() and return; from there

**Comment by joel16** [comment]
Hmm alright, I'll have a look at it this sometime during the weekend :) 
Thanks.

**Comment by joel16** [comment]
Alright so I played along with this for a bit, and I have some things to say about it.

1. I'm sticking to how I load fonts using multiple declarations of the same font using sftd_load_font_mem, until xerpi fixes his issue with sftd. (We can easily change this once he has fixed it)

2. Thanks for reminding me about using the makefile to access system version, compile dates and such :) I altered the compile date however to re-write in a format in which I prefer. example (20160905)

3. I also decided to use a new way of controlling the cursor. It now uses the analog/c-stick/d-pad. Since the touch screen is smaller it wouldn't be able to access all of the top screen, so this is what I'll use for now. However there's one problem when navigation through the x axis. It seems to go no further than 252 on the x axis. It just resets the cursor position to 0 if you try to go beyond that. I'll try to see if I can fix that before submitting my pull request.

4. And is break from main() really the only way to exit homebrew? I was wishing there'd be a function call or something ;p oh well.

**Comment by Wolfvak** [comment]
1. Alright, that's cool. Only problem I can find is that xerpi doesn't appear to be too active currently, and he's actually recommending to switch to citro3d (https://github.com/xerpi/sf2dlib/issues/30#issuecomment-207767618) so I guess it won't get fixed for a while.

2. Yeah, I wasn't sure about it so I just sticked the first date format that crossed my mind and version "0.1" because that's what it was previously. You might wanna change it to "git" or "dev" or something like that, given 0.1 hasn't been reached yet (not released at least).

3. Maybe you should give the cursor it's own coordinates and make those controllable with the analog, that should fix your problem unless you already do this and I misunderstood your issue)
BTW maybe you're using an unsigned char to store the coordinates, which would explain your issue (not sure why 252 instead of 255 but give it a shot)

4. I've looked through the whole source of ctrulib and there's no specific functions to do this. However you may be able to place a setjmp() inside the main loop, and when you want to exit the homebrew just use it

**Comment by joel16** [comment]
Alright I merged your changes along with a few of my modifications. Cursor now works better, and the power menu also exits back to hb launcher properly. It now displays the model and region under settings/about.
https://github.com/joel16/Cyanogen3DS/commit/092229cfd62a074e1ed4decec74a473dfd118dd1

The basic foundation of the program is almost done. Just need to move the navigation bar to the bottom screen entirely, so that it will be a touch screen only thing :p

**Comment by Wolfvak** [comment]
Only thing left that I can think of is to make a sort of "is_in_boundary" function, to replace the cursorX >= ... && ..., just a simple macro should suffice, but maybe an inline function may be required.
This is just to make the code a bit cleaner, and make it easier to add more functions (if you want to, of course).

**Comment by joel16** [comment]
Okay, so now I definitely have most of the basic functionality working ;p It's just that quick settings bit. I just need to find a way to draw gestures on the touch screen. kind of like just drawing a line downwards from the very top to pull it down, and drawing a line upwards to pull it back up. 
And also that file manager is messy af. I don't know why but whenever I draw it, it just freezes, and the only thing it displays is a bunch of lines going down saying (null)
kind of like:
(null)
(null)
(null)
(null)
(null)
(null)

haha, do you have any idea? I was never good at working with file managers anyway haha

**Comment by Wolfvak** [comment]
I really don't know what to say, given that I've never worked with FSUSER but rather have always used newlib's wrappers (fopen, fread, fwrite, etc).

> It's just that quick settings bit

You mean you want to check whether the user swipes down or up, and show or hide the quick settings thing?

**Comment by joel16** [comment]
Haha, yeah FSUSER is new to me as well. Oh well I'll figure it out later. 
And yeah If I can check for the swiping bits,  then I can make the quick settings appear/disappear.

**Comment by joel16** [comment]
I fixed the null bit, I just need to work with the selection and stuff now haha.

**Comment by Wolfvak** [comment]
Did it work with FSUSER?

**Pull request merged**
